[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "my_project"
version = "0.1.0"

[tool.setuptools]
py-modules = ["config"]

[tool.setuptools.packages.find]
where = ["."]
exclude = ["falkodb*", "gdelt_raw"]
include = ["agent*", "schemas*", "pipeline*", "db*"]